# Generated by Django 2.0.13 on 2019-09-28 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=70)),
                ('Last_names', models.CharField(max_length=70)),
                ('IdPersonal', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Start_Work', models.DateTimeField(blank=True, null=True)),
                ('State', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('register', 'register')], default='register', max_length=10)),
                ('Create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('Usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=70)),
                ('Name', models.CharField(max_length=70)),
                ('Description', models.CharField(max_length=70)),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Smin', models.IntegerField(blank=True, null=True)),
                ('Smax', models.IntegerField(blank=True, null=True)),
                ('State', models.CharField(choices=[('inactive', 'Inactive'), ('check', 'Check'), ('active', 'Active')], default='check', max_length=10)),
                ('Pprice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Sprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('Create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.AsignBrand')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=50, unique=True)),
                ('Last_names', models.CharField(max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('DPI', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Create', models.DateTimeField(blank=True, null=True)),
                ('Distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Distributor')),
            ],
        ),
        migrations.AddField(
            model_name='asignbrand',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Brand'),
        ),
        migrations.AddField(
            model_name='asignbrand',
            name='Distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Distributor'),
        ),
    ]
