# Generated by Django 2.0.13 on 2019-10-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
