# Generated by Django 2.0.13 on 2019-10-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20191026_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='Phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='State',
            field=models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo'), ('Registro', 'Registro')], default='register', max_length=10),
        ),
    ]
