# Generated by Django 2.0.13 on 2019-10-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20191026_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
