# Generated by Django 2.0.13 on 2019-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20191026_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Start_Work',
            field=models.DateField(blank=True, null=True),
        ),
    ]
